name: Build Vite Site

on:
  push:
    branches: '*'

  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Checkout dist branch
        uses: actions/checkout@v5
        with:
          ref: 'dist'

      - name: Copy build to branch
        run: |
          git rm -rf .
          git checkout main -- dist/*
          git commit -m "Vite build"